/**
 * src/config/constants.ts
 * * Static data used across the application.
 * These IDs correspond strictly to the IGDB database IDs.
 * Hardcoded to save API calls for data that rarely changes.
 */

export const PLATFORMS = [
  // --- 1st gen (1972–1980) ---
  { id: 88, name: 'Odyssey' },
  { id: 140, name: 'AY-3-8500' },
  { id: 145, name: 'AY-3-8603' },
  { id: 146, name: 'AY-3-8605' },
  { id: 147, name: 'AY-3-8606' },
  { id: 148, name: 'AY-3-8607' },
  { id: 141, name: 'AY-3-8610' },
  { id: 144, name: 'AY-3-8710' },
  { id: 143, name: 'AY-3-8760' },
  { id: 142, name: 'PC-50X Family' },
  { id: 505, name: 'Elektor TV Games Computer' },

  // --- 2nd gen (1976–1992) ---
  { id: 127, name: 'Fairchild Channel F' },
  { id: 59, name: 'Atari 2600' },
  { id: 91, name: 'Bally Astrocade' },
  { id: 139, name: '1292 Advanced Programmable Video System' },
  { id: 133, name: 'Odyssey 2 / Videopac G7000' },
  { id: 67, name: 'Intellivision' },
  { id: 89, name: 'Microvision' },
  { id: 375, name: 'Epoch Cassette Vision' },
  { id: 70, name: 'Vectrex' },
  { id: 473, name: 'Arcadia 2001' },
  { id: 68, name: 'ColecoVision' },
  { id: 66, name: 'Atari 5200' },
  { id: 60, name: 'Atari 7800' },
  { id: 65, name: 'Atari 8-bit' },
  { id: 129, name: 'Texas Instruments TI-99' },
  { id: 126, name: 'TRS-80' },
  { id: 151, name: 'TRS-80 Color Computer' },
  { id: 90, name: 'Commodore PET' },
  { id: 71, name: 'Commodore VIC-20' },
  { id: 85, name: 'Donner Model 30' },
  { id: 100, name: 'Analogue electronics' },

  // --- 3rd gen (1983–2003) ---
  { id: 99, name: 'Family Computer' },
  { id: 18, name: 'Nintendo Entertainment System' },
  { id: 64, name: 'Sega Master System/Mark III' },
  { id: 84, name: 'SG-1000' },
  { id: 376, name: 'Epoch Super Cassette Vision' },
  { id: 51, name: 'Family Computer Disk System' },
  { id: 13, name: 'DOS' },
  { id: 25, name: 'Amstrad CPC' },
  { id: 69, name: 'BBC Microcomputer System' },
  { id: 15, name: 'Commodore C64/128/MAX' },
  { id: 93, name: 'Commodore 16' },
  { id: 94, name: 'Commodore Plus/4' },
  { id: 110, name: 'PLATO' },
  { id: 102, name: 'EDSAC' },
  { id: 101, name: 'Ferranti Nimrod Computer' },
  { id: 112, name: 'Microcomputer' },
  { id: 26, name: 'ZX Spectrum' },
  { id: 373, name: 'Sinclair ZX81' },
  { id: 152, name: 'FM-7' },

  // --- 4th gen (1987–2004) ---
  { id: 86, name: 'TurboGrafx-16/PC Engine' },
  { id: 128, name: 'PC Engine SuperGrafx' },
  { id: 150, name: 'Turbografx-16/PC Engine CD' },
  { id: 29, name: 'Sega Mega Drive/Genesis' },
  { id: 78, name: 'Sega CD' },
  { id: 30, name: 'Sega 32X' },
  { id: 482, name: 'Sega CD 32X' },
  { id: 19, name: 'Super Nintendo Entertainment System' },
  { id: 58, name: 'Super Famicom' },
  { id: 131, name: 'Super NES CD-ROM System' },
  { id: 80, name: 'Neo Geo AES' },
  { id: 79, name: 'Neo Geo MVS' },
  { id: 33, name: 'Game Boy' },
  { id: 61, name: 'Atari Lynx' },
  { id: 35, name: 'Sega Game Gear' },
  { id: 506, name: 'Amstrad GX4000' },
  { id: 480, name: 'Super A\'Can' },
  { id: 408, name: 'Mega Duck/Cougar Boy' },
  { id: 16, name: 'Amiga' },
  { id: 63, name: 'Atari ST/STE' },
  { id: 27, name: 'MSX' },
  { id: 53, name: 'MSX2' },
  { id: 125, name: 'PC-8800 Series' },
  { id: 149, name: 'PC-9800 Series' },
  { id: 121, name: 'Sharp X68000' },
  { id: 77, name: 'Sharp X1' },

  // --- 5th gen (1993–2006) ---
  { id: 50, name: '3DO Interactive Multiplayer' },
  { id: 114, name: 'Amiga CD32' },
  { id: 62, name: 'Atari Jaguar' },
  { id: 410, name: 'Atari Jaguar CD' },
  { id: 32, name: 'Sega Saturn' },
  { id: 7, name: 'PlayStation' },
  { id: 4, name: 'Nintendo 64' },
  { id: 416, name: '64DD' },
  { id: 380, name: 'Casio Loopy' },
  { id: 476, name: 'Apple Pippin' },
  { id: 87, name: 'Virtual Boy' },
  { id: 136, name: 'Neo Geo CD' },
  { id: 379, name: 'Game.com' },
  { id: 117, name: 'Philips CD-i' },
  { id: 122, name: 'Nuon' },
  { id: 274, name: 'PC-FX' },
  { id: 308, name: 'Playdia' },
  { id: 118, name: 'FM Towns' },
  { id: 158, name: 'Commodore CDTV' },
  { id: 378, name: 'Gamate' },
  { id: 475, name: 'R-Zone' },

  // --- 6th gen (1998–2015) ---
  { id: 23, name: 'Dreamcast' },
  { id: 8, name: 'PlayStation 2' },
  { id: 21, name: 'Nintendo GameCube' },
  { id: 11, name: 'Xbox' },
  { id: 24, name: 'Game Boy Advance' },
  { id: 22, name: 'Game Boy Color' },
  { id: 119, name: 'Neo Geo Pocket' },
  { id: 120, name: 'Neo Geo Pocket Color' },
  { id: 57, name: 'WonderSwan' },
  { id: 123, name: 'WonderSwan Color' },
  { id: 124, name: 'SwanCrystal' },
  { id: 42, name: 'N-Gage' },
  { id: 44, name: 'Tapwave Zodiac' },
  { id: 441, name: 'PocketStation' },
  { id: 440, name: 'Visual Memory Unit / Visual Memory System' },
  { id: 240, name: 'Zeebo' },

  // --- 7th gen (2004–2017) ---
  { id: 12, name: 'Xbox 360' },
  { id: 9, name: 'PlayStation 3' },
  { id: 5, name: 'Wii' },
  { id: 20, name: 'Nintendo DS' },
  { id: 159, name: 'Nintendo DSi' },
  { id: 38, name: 'PlayStation Portable' },
  { id: 306, name: 'Satellaview' },
  { id: 439, name: 'V.Smile' },
  { id: 74, name: 'Windows Phone' },
  { id: 73, name: 'BlackBerry OS' },

  // --- 8th gen (2011–PRESENTE) ---
  { id: 37, name: 'Nintendo 3DS' },
  { id: 137, name: 'New Nintendo 3DS' },
  { id: 46, name: 'PlayStation Vita' },
  { id: 41, name: 'Wii U' },
  { id: 48, name: 'PlayStation 4' },
  { id: 49, name: 'Xbox One' },
  { id: 130, name: 'Nintendo Switch' },
  { id: 72, name: 'Ouya' },
  { id: 170, name: 'Google Stadia' },
  { id: 203, name: 'DUPLICATE Stadia' },
  { id: 309, name: 'Evercade' },
  { id: 381, name: 'Playdate' },
  { id: 132, name: 'Amazon Fire TV' },
  { id: 389, name: 'AirConsole' },
  { id: 164, name: 'Daydream' },

  // --- 9th gen (2020–PRESENTE) ---
  { id: 167, name: 'PlayStation 5' },
  { id: 169, name: 'Xbox Series X|S' },
  { id: 508, name: 'Nintendo Switch 2' },
  { id: 471, name: 'Meta Quest 3' },
  { id: 390, name: 'PlayStation VR2' },
  { id: 472, name: 'visionOS' },

  // --- Modern computers & phones ---
  { id: 6, name: 'PC (Microsoft Windows)' },
  { id: 3, name: 'Linux' },
  { id: 14, name: 'Mac' },
  { id: 34, name: 'Android' },
  { id: 39, name: 'iOS' },
  { id: 55, name: 'Legacy Mobile Device' },
  { id: 82, name: 'Web browser' },
  { id: 405, name: 'Windows Mobile' },
  { id: 417, name: 'Palm OS' },

  // --- VR ---
  { id: 165, name: 'PlayStation VR' },
  { id: 386, name: 'Meta Quest 2' },
  { id: 384, name: 'Oculus Quest' },
  { id: 385, name: 'Oculus Rift' },
  { id: 387, name: 'Oculus Go' },
  { id: 162, name: 'Oculus VR' },
  { id: 163, name: 'SteamVR' },
  { id: 161, name: 'Windows Mixed Reality' },
  { id: 388, name: 'Gear VR' },

  // --- Arcade ---
  { id: 52, name: 'Arcade' },
  { id: 135, name: 'Hyper Neo Geo 64' },
  { id: 372, name: 'OOParts' },

  // --- classic microcomputers ---
  { id: 116, name: 'Acorn Archimedes' },
  { id: 134, name: 'Acorn Electron' },
  { id: 154, name: 'Amstrad PCW' },
  { id: 115, name: 'Apple IIGS' },
  { id: 153, name: 'Dragon 32/64' },
  { id: 236, name: 'Exidy Sorcerer' },
  { id: 157, name: 'NEC PC-6000 Series' },
  { id: 374, name: 'Sharp MZ-2200' },
  { id: 155, name: 'Tatung Einstein' },
  { id: 156, name: 'Thomson MO5' },
  { id: 107, name: 'Call-A-Computer time-shared mainframe computer system' },
  { id: 109, name: 'CDC Cyber 70' },
  { id: 98, name: 'DEC GT40' },
  { id: 104, name: 'HP 2100' },
  { id: 105, name: 'HP 3000' },
  { id: 111, name: 'Imlac PDS-1' },
  { id: 106, name: 'SDS Sigma 7' },
  { id: 95, name: 'PDP-1' },
  { id: 96, name: 'PDP-10' },
  { id: 108, name: 'PDP-11' },
  { id: 103, name: 'PDP-7' },
  { id: 97, name: 'PDP-8' },
  { id: 237, name: 'Sol-20' },

  // --- Education and others ---
  { id: 339, name: 'Sega Pico' },
  { id: 507, name: 'Advanced Pico Beena' },
  { id: 412, name: 'Leapster' },
  { id: 413, name: 'Leapster Explorer/LeadPad Explorer' },
  { id: 414, name: 'LeapTV' },
  { id: 438, name: 'Arduboy' },
  { id: 486, name: 'Digiblast' },
  { id: 487, name: 'LaserActive' },
  { id: 479, name: 'Terebikko / See \'n Say Video Phone' },
  { id: 481, name: 'Tomy Tutor / Pyuta / Grandstand Tutor' },
  { id: 504, name: 'Uzebox' },
  { id: 407, name: 'HyperScan' },
  { id: 409, name: 'Legacy Computer' },
  { id: 509, name: 'Polymega' },
  { id: 377, name: 'Plug & Play' },
  { id: 166, name: 'Pokémon mini' },
  { id: 238, name: 'DVD Player' },
  { id: 239, name: 'Blu-ray Player' },
  { id: 510, name: 'e-Reader / Card-e Reader' },
  { id: 138, name: 'VC 4000' },
  { id: 477, name: 'Panasonic Jungle' },
  { id: 478, name: 'Panasonic M2' }
];

export const GENRES = [
  { id: 2, name: 'Point-and-click' },
  { id: 4, name: 'Fighting' },
  { id: 5, name: 'Shooter' },
  { id: 7, name: 'Music' },
  { id: 8, name: 'Platform' },
  { id: 9, name: 'Puzzle' },
  { id: 10, name: 'Racing' },
  { id: 11, name: 'Real Time Strategy (RTS)' },
  { id: 12, name: 'Role-playing (RPG)' },
  { id: 13, name: 'Simulator' },
  { id: 14, name: 'Sport' },
  { id: 15, name: 'Strategy' },
  { id: 16, name: 'Turn-based strategy (TBS)' },
  { id: 24, name: 'Tactical' },
  { id: 25, name: "Hack and slash/Beat 'em up" },
  { id: 26, name: 'Quiz/Trivia' },
  { id: 30, name: 'Pinball' },
  { id: 31, name: 'Adventure' },
  { id: 32, name: 'Indie' },
  { id: 33, name: 'Arcade' },
  { id: 34, name: 'Visual Novel' },
  { id: 35, name: 'Card & Board Game' },
  { id: 36, name: 'MOBA' },
];

export const THEMES = [
  { id: 17, name: 'Fantasy' },
  { id: 18, name: 'Science fiction' },
  { id: 19, name: 'Horror' },
  { id: 20, name: 'Thriller' },
  { id: 21, name: 'Survival' },
  { id: 22, name: 'Historical' },
  { id: 23, name: 'Stealth' },
  { id: 27, name: 'Comedy' },
  { id: 28, name: 'Business' },
  { id: 31, name: 'Drama' },
  { id: 32, name: 'Non-fiction' },
  { id: 33, name: 'Sandbox' },
  { id: 34, name: 'Educational' },
  { id: 35, name: 'Kids' },
  { id: 38, name: 'Open world' },
  { id: 39, name: 'Warfare' },
  { id: 40, name: 'Party' },
  { id: 41, name: '4X (Explore, Expand, Exploit, Exterminate)' },
  { id: 42, name: 'Erotic' },
  { id: 43, name: 'Mystery' },
  { id: 44, name: 'Romance' },
];

export const GAME_MODES = [
  { id: 1, name: 'Single player' },
  { id: 2, name: 'Multiplayer' },
  { id: 3, name: 'Co-operative' },
  { id: 4, name: 'Split screen' },
  { id: 5, name: 'Massively Multiplayer Online (MMO)' },
  { id: 6, name: 'Battle Royale' },
];

export const PERSPECTIVES = [
  { id: 1, name: 'First person' },
  { id: 2, name: 'Third person' },
  { id: 3, name: 'Bird view / Isometric' },
  { id: 4, name: 'Side view' },
  { id: 5, name: 'Text' },
  { id: 6, name: 'Auditory' },
  { id: 7, name: 'Virtual Reality' },
];

export const AGE_RATING_ORGANIZATIONS = [
  { id: 1, name: 'ESRB' },
  { id: 2, name: 'PEGI' },
  { id: 3, name: 'CERO' },
  { id: 4, name: 'USK' },
  { id: 5, name: 'GRAC' },
  { id: 6, name: 'CLASS IND' },
  { id: 7, name: 'ACB' },
];

export const AGE_RATING_VALUES = [
  // ESRB (Organization 1)
  { id: 1, name: 'RP' },
  { id: 2, name: 'EC' },
  { id: 3, name: 'E' },
  { id: 4, name: 'E10+' },
  { id: 5, name: 'T' },
  { id: 6, name: 'M' },
  { id: 7, name: 'AO' },

  // PEGI (Organization 2)
  { id: 8, name: '3' },
  { id: 9, name: '7' },
  { id: 10, name: '12' },
  { id: 11, name: '16' },
  { id: 12, name: '18' },

  // CERO (Organization 3)
  { id: 13, name: 'A' },
  { id: 14, name: 'B' },
  { id: 15, name: 'C' },
  { id: 16, name: 'D' },
  { id: 17, name: 'Z' },

  // USK (Organization 4)
  { id: 18, name: '0' },
  { id: 19, name: '6' },
  { id: 20, name: '12' },
  { id: 21, name: '16' },
  { id: 22, name: '18' },

  // GRAC (Organization 5)
  { id: 23, name: 'ALL' },
  { id: 24, name: '12+' },
  { id: 25, name: '15+' },
  { id: 26, name: '19+' },
  { id: 40, name: '18+' },
  { id: 27, name: 'TESTING' },

  // CLASS IND (Organization 6)
  { id: 28, name: 'L' },
  { id: 29, name: '10' },
  { id: 30, name: '12' },
  { id: 31, name: '14' },
  { id: 32, name: '16' },
  { id: 33, name: '18' },

  // ACB (Organization 7)
  { id: 34, name: 'G' },
  { id: 35, name: 'PG' },
  { id: 36, name: 'M' },
  { id: 37, name: 'MA 15+' },
  { id: 38, name: 'R 18+' },
  { id: 39, name: 'RC' }
];

export const GAME_CATEGORIES = [
  { id: 0, name: 'Main Game' },
  { id: 1, name: 'DLC / Addon' },
  { id: 2, name: 'Expansion' },
  { id: 3, name: 'Bundle' },
  { id: 4, name: 'Standalone Expansion' },
  { id: 5, name: 'Mod' },
  { id: 6, name: 'Episode' },
  { id: 7, name: 'Season' },
  { id: 8, name: 'Remake' },
  { id: 9, name: 'Remaster' },
  { id: 10, name: 'Expanded Game' },
  { id: 11, name: 'Port' },
  { id: 12, name: 'Fork' },
  { id: 13, name: 'Pack' },
  { id: 14, name: 'Update' },
];

export const GAME_STATUSES = [
  { id: 0, name: 'Released' },
  { id: 2, name: 'Alpha' },
  { id: 3, name: 'Beta' },
  { id: 4, name: 'Early Access' },
  { id: 5, name: 'Offline' },
  { id: 6, name: 'Cancelled' },
  { id: 7, name: 'Rumored' },
  { id: 8, name: 'Delisted' },
];